language: clojure
script: bash ./deploy_dox.sh
env:
  global:
    GH_REF: github.com/monteithpj/asystant.git
    secure: 0+JvkFM+8haJvd5fCbbAaFygRWs8eftNrJjO7dnIVy/NhzLZwbFBRv1tsQMQ65QLifN1/t5gry3YHOBiR3H4wTlwMMC/ixbuxis2Va9bJKKLMsx3atIH0qH40fF8EjXK9cOfL/xjbyd66XXHc5Mh/MecveLKqIUzsQGPRmm9ESHR+o3y1UVKw5Iuk2fEleEnhmuyUWj7WQqnYNrkYJg4r8oiE79CxpDP3bIIGYMBDiJ4HSHn2R9lzx+WvMuBb91FbNEiD/nh/0YMLwFCu42dQOofiuvLE95TAnv4uMKKdLRDFjrbRIyCOnSbVxKZJfgY4LfELicO0eW8VV5wajFTUzFkS+3g7KYoKZxXrA2pSxn6+nvhcMtNmepPSEwM90poI87BRGwYhCopChkTlGlHw5uZi6IvqDm9V/2ddVJDtv2vR6AiL4P3w3m8Orh2rn1z5Sn1B+wtzc3FtNqT8WDtEbeh0877vxu/DBS7GnOWezYSO+jVpoKuusC91pKdW0Oxa/kfA2fJwuIhl5Aqx5NsU/J7Y9oPc8Uj4kjqpSJLt2Q90nRoH3onOnE8N9KNx1hhUjcY1cWCl9esLLn/+QCSgguVS0OliUwkSp1BB61AutjIM+QXBIOW4UhV61/n0TIwWffnsOP0kjueXckscofBAfXI3raCurF08A6m3L1w5pg=
