language: clojure
after_script: bash ./deploy_dox.sh
env:
  global:
  - GH_REF: github.com/monteithpj/asystant.git
  - secure: lXSDGeaXtn+gRMhEfmV4lC/nIwz4YJOGmjcqpm73V9HHfA3LLRD/e44PD1tMlKC5ja8gYVot7fVY/Lnqr7uhOYpkq2YCsrTzvQxzfSaNTC9L2wt5ln3Fl4eeXlu0l8JAwMA1LHhafwWekxC8YeG1qsTbTxptfM9LQtlVzsvbXBkSF++VvSRirwQzujr8m1lg0iDPbS21QjCg607lWj4z5mpH73LJi044uKou+EMiNChEor7mTYlVVAuRoLxM4S7Ct7PBjb2twQZ9GbbEP2smE3n35GZSU9Y5I0mParmlVJASjSTcUH9kTzpS7cOD1jnHV5Zp5iBq1/mwQU70Y9A+1NJc8t9Ifzlq2F/hAQVmviE3UN3bk0Nayb8tXVGSRicK2/5aYnZJP4/4wvIk7eBgk5RazbLT8TDPFvUh/4lCDrddOqv2tc4AUie3JVIiIfnXqf7dgUkxnA2dYsntcVp4ydGzrabFZVnKJKMRoSorPQocTrXgvT01PY+mXiGSRt4z4v23k682sJDHIPOeQP3QkabLA7Apecw5ZrcQRpNlziLZZ/X6y/AuHadGhKsO9FxiYr1kI7ptduv1KIB/eI2cEMxV1Ck+0bcWHkoR2xoZFcdu8tjD1mqa75oyQdMGD1P3R+dshLGkQuLG5TRpPZsukC4fJhHqKCCyw9zr7sMpRpM=
